name:                telemetry
version:             0.1.0.0
github:              "psuggate/telemetry"
license:             BSD-3-Clause
author:              "Patrick Suggate"
maintainer:          "patrick.suggate@gmail.com"
copyright:           "2022 Patrick Suggate"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/psuggate/telemetry#readme>

default-extensions:
- DataKinds
- DeriveGeneric
- NoImplicitPrelude
- TemplateHaskell

dependencies:
- base >= 4.7 && < 5
- lens
- relude
# - streamly >= 0.10 && < 0.11
- text
- vector

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  telemetry-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - telemetry

tests:
  telemetry-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - telemetry
